// <auto-generated />
using System;
using AdaMuzik.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaMuzik.Migrations
{
    [DbContext(typeof(AdaMuzikContext))]
    partial class AdaMuzikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdaMuzik.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ad");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("cikis_tarihi");

                    b.Property<int>("SanatciId")
                        .HasColumnType("int")
                        .HasColumnName("sanatci_id");

                    b.HasKey("Id");

                    b.HasIndex("SanatciId");

                    b.ToTable("albumler");
                });

            modelBuilder.Entity("AdaMuzik.Models.CalmaListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ad");

                    b.HasKey("Id");

                    b.ToTable("calma_listeleri");
                });

            modelBuilder.Entity("AdaMuzik.Models.CalmaListesiSarkisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalmaListesiId")
                        .HasColumnType("int")
                        .HasColumnName("calma_listesi_id");

                    b.Property<int>("SarkiId")
                        .HasColumnType("int")
                        .HasColumnName("sarki_id");

                    b.HasKey("Id");

                    b.HasIndex("CalmaListesiId");

                    b.HasIndex("SarkiId");

                    b.ToTable("calma_listeleri_sarkilari");
                });

            modelBuilder.Entity("AdaMuzik.Models.Sanatci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ad");

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("kurulus_tarihi");

                    b.HasKey("Id");

                    b.ToTable("sanatcilar");
                });

            modelBuilder.Entity("AdaMuzik.Models.Sarki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ad");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int")
                        .HasColumnName("album_id");

                    b.Property<int>("SanatciId")
                        .HasColumnType("int")
                        .HasColumnName("sanatci_id");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("SanatciId");

                    b.ToTable("sarkilar");
                });

            modelBuilder.Entity("AdaMuzik.Models.Album", b =>
                {
                    b.HasOne("AdaMuzik.Models.Sanatci", "Sanatci")
                        .WithMany("Albumler")
                        .HasForeignKey("SanatciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sanatci");
                });

            modelBuilder.Entity("AdaMuzik.Models.CalmaListesiSarkisi", b =>
                {
                    b.HasOne("AdaMuzik.Models.CalmaListesi", "CalmaListesi")
                        .WithMany("CalmaListeleriSarkilari")
                        .HasForeignKey("CalmaListesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdaMuzik.Models.Sarki", "Sarki")
                        .WithMany("CalmaListeleriSarkilari")
                        .HasForeignKey("SarkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalmaListesi");

                    b.Navigation("Sarki");
                });

            modelBuilder.Entity("AdaMuzik.Models.Sarki", b =>
                {
                    b.HasOne("AdaMuzik.Models.Album", "Album")
                        .WithMany("Sarkilar")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdaMuzik.Models.Sanatci", "Sanatci")
                        .WithMany("Sarkilar")
                        .HasForeignKey("SanatciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Sanatci");
                });

            modelBuilder.Entity("AdaMuzik.Models.Album", b =>
                {
                    b.Navigation("Sarkilar");
                });

            modelBuilder.Entity("AdaMuzik.Models.CalmaListesi", b =>
                {
                    b.Navigation("CalmaListeleriSarkilari");
                });

            modelBuilder.Entity("AdaMuzik.Models.Sanatci", b =>
                {
                    b.Navigation("Albumler");

                    b.Navigation("Sarkilar");
                });

            modelBuilder.Entity("AdaMuzik.Models.Sarki", b =>
                {
                    b.Navigation("CalmaListeleriSarkilari");
                });
#pragma warning restore 612, 618
        }
    }
}
